matrix:
  include:
    - language: python

      python:
        - 3.8

      services:
        - docker
        - mysql

      install:
        - docker-compose up -d channel
        - pip install -r requirements.txt

      before_script:
        - mysql -e 'CREATE DATABASE test;' -u root

      script:
        - bash scripts/test.sh

      after_script:
        - coveralls
        
      deploy:
        provider: heroku
        api_key:
          secure: aiXLE3S8tB3PDdhMrtcmKO9275Q0Sqpc2J+Tx/eea7x+X/cYhwbAqArgQrkOdMsKaJAJVtZX8gXIbzGfV815+0rKY4htFuneSsQooMqhqngbf3IremVFhvz1JyvTK0iR00Q4LWd2IOQlL7QFmvPSvVMS44V6LaObGt91Wa0Vj7kbWBIgASwqFV3TtLJTIQXrj3fl2lkUIrqk/mf+iSyInSHfrAaOHH8KTnqqcTRXJsKRzADjKak0n/oB6DefaLL23/E4h+9Ie7hUPI6bgT3HO4OLWv0ZRsLSzwhEafSAy9Le0X4Bz8v9eXfC6663xbzUhZg4fDprRL2R4aaJSS/4I3775BL4XRhIC0EUFaR2xoFbfX9usXsV8J49RIImqHE84k5FB/Oe8XimCnyruMPqmF6XPruR76BTLN6rCNgVyxmAWk3k5HG3/v9z+Yv2Kfwl4JW5Ff+PgCtS6fYY54AEzouqAxuYygDwxNRh1CkwJfIEjcJQ3FgqHogE54x1bAQ2En4lD38SUtniTbyDU5Vx21QvM1hVZvxxG1EukMDCZ2+wbW3TfHhySOAj4UMe34IDW+1bpygFvgSPIHi2UWu3Ort7By3GPpYMde7Meg+zcu7UVCx4fJIk9eRVzMyV2vAabOQFcrjUBSpnnexaZomuSXyblY3CEM4w09Jtzvnx2lo=
        app: k-chatapp
        on: dev

    - language: node_js

      node_js:
        - 10

      before_install:
        - cd frontend

      script:
        - yarn test-coverage

notifications:
  email:
    on_success: never
    on_failure: never