version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./db_data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kchat
    ports:
      - "3306:3306"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8888:80"
    links:
      - db

  channel:
    image: redis:5
    ports:
     - "6379:6379"

  web:
    build: .
    command: bash -c "bash rm-cr.sh && bash scripts/start-web.sh"
    volumes:
      - .:/home/kchat
    ports:
      - "8000:8000"
    depends_on:
      - db
      - channel

  frontend:
    build:
      context: frontend
    command: sh -c "yarn && yarn start --host 0.0.0.0 --port 8080 --inline --hot"
    ports:
      - "8080:8080"
    depends_on:
      - web
      
volumes:
  db_data: