version: '3.7'

services:
  channel:
    image: redis:5
    ports:
     - "6379:6379"

  web:
    build: .
    command: bash -c "bash rm-cr.sh && bash scripts/start-web.sh"
    volumes:
      - .:/home/kchat
    ports:
      - "8000:8000"
    depends_on:
      - channel
<<<<<<< HEAD
=======

  frontend:
    build:
      context: frontend
    command: sh -c "yarn && yarn start --host 0.0.0.0 --port 8080 --inline --hot"
    ports:
      - "8080:8080"
    depends_on:
      - web
>>>>>>> dev
      
volumes:
  db_data: