# Generated by Django 2.2 on 2020-04-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='request_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
