# Generated by Django 2.2 on 2020-04-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='order_in_conversation',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
