# Generated by Django 3.0.5 on 2020-04-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_participant_request_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='request_message',
        ),
        migrations.AddField(
            model_name='connection',
            name='request_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
