# Generated by Django 2.2 on 2020-04-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200422_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
