# Generated by Django 2.2 on 2020-04-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200420_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='', max_length=40),
        ),
    ]
