# Generated by Django 2.2 on 2020-04-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='last_seen_message_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
